LOSS:
  DYNAMIC_EPSILON: true
  TEMP_MIN: 0.3
  TEMP_MAX: 3.0
# WANDB:
#   NAME: "exp_C_temperature_sweep" # Temperature sweep 실험
#   TAGS: ["temperature_sweep", "dynamic_epsilon"]
#   ENABLE: True
#   PROJECT: "ccreid"
